hive-mind-fs/hive-mind

db/models/game.js, db/models/index.js, db/models/round.js, db/models/user.js, db/models/word.js, gitmasterToDos
=> Delete local file

server/db/models/index.js, server/db/models/index.spec.js
We cant run the test rn.
What are you doing for that?
=> Test alphabetization

.travis.yaml, server/db/models/user.js
Initial travis setup to see if pr's work
=> Initial Travis

server/db/models/index.js, server/db/models/index.spec.js, server/db/models/userRound.js
=> Finish model associations rebased

server/db/models/guessedWord.js, server/db/models/index.js, server/db/models/index.spec.js, server/db/models/round.js, server/db/models/round.spec.js, server/db/models/word.js, server/db/models/word.spec.js
=> Alphabetize letters, round winners, test last association

client/App.js, client/screens/CountdownScreen.js, client/screens/DashboardScreen.js, client/screens/Game.js, client/screens/GameBoardScreen.js, client/screens/LandingScreen.js, client/screens/index.js, client/store/game.js, client/store/store.js
- Configured countdown screen with 3 second local countdownTimer state, which redirects after the countdown ends.
- Added Game.js file where I think we should house parent game state.
- Added game.js store file skeleton.
Close #51
=> Completed Game Countdown Timer

client/components/RoundScore.js, client/screens/GameBoardScreen.js
=> Gameplay logic

client/screens/GameBoardScreen.js
=> Added round timer with redirect to GameBoard

README.md, client/screens/GameBoardScreen.js
added the logic to dynamically display your rank based on the precentage of possible points for the board
=> Scoring logic

client/screens/GameBoardScreen.js
=> Gameplay errors

client/screens/GameBoardScreen.js, client/screens/GameBoardScreens.spec.js
Attempted to make logic for setting your rank less heavy handed.
=> Rank algo+

client/screens/GameBoardScreen.js, client/screens/gameBoardController.js, client/screens/gameBoardController.spec.js, package.json
Let's modularize!!!
Some examples for how we can refactor our components
=> Game board refactor

client/screens/GameBoardScreen.js
@rhanixon should be in a good enough place to start refactor
=> Small fix hook up redux state

client/screens/GameBoardScreen.js
Redux state passed via props
Local state managed by this.state initialized in constructor
=> Move state into constructor

client/screens/GameBoardScreen.js, client/screens/gameBoardController.js
To do:
- reimplement game time using useEffect
=> Refactor game board hooks

client/screens/GameBoardScreen.js, client/screens/PlayScreen.js, client/screens/gameBoardController.js, client/store/game.js, server/api/userRounds.js
Post/Put to database based on user from redux state
=> Get user from state

README.md
Do i need to  include information like download Xcode?
=> Add series of instructions for building app locally

client/utils/styles.js
=> Error fix1

client/App.js, client/screens/PlayScreen.js, client/store/user.js, server/auth/index.js
Implement logout
Fix some other miscellaneous bugs
=> Logout and misc bugs

client/screens/GameBoardScreen.js, client/screens/LandingScreen.js, client/screens/PostRoundScreen.js, client/screens/gameBoardController.js, dictionary/utils.js
Closes #190 
Plugged in pangramList and possiblePoints to gameBoardController and View.
=> Games work

dictionary/scriptHashMap.js, script/seed.js
=> Associate words correctly

dictionary/deploy, dictionary/index.js, dictionary/scriptHashMap.js, dictionary/utils.js, script/seed.js
Streaming worked. Thanks @richmcateer 
can we deploy this to 'roku
=> Stream pangram words to file

client/screens/HomeScreen.js, client/screens/LoginScreen.js, client/screens/PlayScreen.js, client/store/game.js, package.json, script/seed.js, server/api/index.js, server/api/userRounds.js
=> Userround seeding

client/screens/GameBoardScreen.js, client/screens/PracticeRoundScreen.js
Client side logic works for all uppercase
=> All uppercase now

client/screens/PostRoundScreen.js, client/screens/PracticeRoundScreen.js
- Fixed display issue with <stats> component
- Ported styling over from 1v1 Post Round
=> Updated practice post round screen

client/screens/CountdownScreen.js, client/screens/GameBoardScreen.js, client/screens/PostRound1v1Screen.js, client/screens/PostRoundScreen.js, client/screens/PracticeRoundScreen.js, client/screens/postRoundUtils.js
To do:
- pass opponents' words via sockets
=> Fix post round screens
